### ISSUE TITLE
Error dos usuarios

### ISSUE THREAD

**Issue by egromero** [egromero/Tarea07#10]
el siguiente dice bla bla IndexError: list index out of range

**Comment by egromero** [comment]
Intentaste con esto?: http://www.bing.com/cr?IG=423FFE57F7E9412099DAD36A10923B3E&CID=104A03F13CBA65282DE6095C3DBC6451&rd=1&h=E2sfg_xd56N5DZ7SToAiX1IORWFnMtDcR8JuZH6-2JY&v=1&r=http%3a%2f%2fwww.r-tutor.com%2fr-introduction%2flist&p=DevEx,5068.1

 Saludos @metalbass_bot

**Comment by Eg-rs** [comment]
Soy otro usuario que comenta aquí
